### ISSUE TITLE
When will the full dataset be uploaded?

### ISSUE THREAD

**Issue by Zxkai** [hmf21/UAVLocalization#3]
Hi，

I am very interested in your project and have been exploring it with great enthusiasm. However, I noticed that the full dataset has not yet been uploaded. Could you please let me know when you plan to upload the complete dataset? Having access to the full data would be very helpful for my research.

Thank you~

**Comment by hmf21** [comment]
Hi @Zxkai ,

Thanks very much for your interest to our project and I am happy to assist your research.
Unfortunately, we are not able to release the flight data in Beijing. Therefore, we only give two public data from Ageagle in this repo.
However, we have given another flight dataset [AerialVL](https://github.com/hmf21/AerialVL), which is self-collected in Qingdao.
This dataset is with more adequent flight data and easy to give different evaluations.
Such dataset has been accepted by RA-L 2024 and we will release the full dataset after the early version is published.

**Comment by Zxkai** [comment]
@hmf21 

Thank you very much for your prompt response and for providing the additional details!!!  I completely understand the restrictions about the Beijing dataset and appreciate your efforts to share alternative data sources.
I wonder if the other datasets mentioned in the paper "_Leveraging Map Retrieval and Alignment for Robust UAV Visual Geo-Localization_", which are used to train and evaluate the models, will be made publicly available? 
![image](https://github.com/user-attachments/assets/a22c20e5-5576-4eb1-8d3f-3e0c2213a090)
Thank you again, and I hope I haven't disturbed you.

**Comment by hmf21** [comment]
Sure, the training dataset is also one part of the AerialVL dataset, which will be released as well.
And we give more details about the training in AerialVL article, which won't take too much time to be published.

**Comment by Zxkai** [comment]
Great!! Looking forward to the publication of your paper and the release of the AerialVL dataset.
