### ISSUE TITLE
关于NETVLAD训练以及检索数据库的问题

### ISSUE THREAD

**Issue by huangk77** [hmf21/UAVLocalization#8]
非常感谢您的工作，给了我们在无人机视觉定位研究很多启发，然而我在尝试使用NETVLAD做检索的时候，发现了仍然有一些问题，想向您请教一下，不知能否解惑？
1. 我们在训练NETVLAD的时候，发现对于查询图像，相对数据库图像中存在较大的旋转变化时，往往难以检索到，这是否与NETVLAD的网络架构有关，请问您是否也有遇到类似的问题？此外，在未知高度的情况下（无气压计），NETVLAD貌似对尺度的变化也会敏感一些。

2. 对于无人机视觉定位的数据库应该怎么样分割才是一个好的数据库呢？我尝试过不重叠，以及重叠的分割方式，发现都会面临旋转的问题，对于较大偏转角度90-180度，网络训练过程中往往难以收敛，我不太确定是否需要将无人机图像和卫星图像两个视角方向对齐？

3. 另外，尽管NETVLAD的参数量不是特别庞大，我们也发现其在嵌入式系统上仍然难以实现，特别是对于其中神经网络给出的聚类中心点，我不确定将这些参数作为固定参数在NPU中作为缓存数据是否合理。。

多有打扰！再次感谢您的贡献！

**Comment by hmf21** [comment]
Hi @huangk77 
您好，感谢您的关注，虽然目前我们暂时不准备公开相应的代码，但我尽可能回复您的问题，请您见谅。
问题1、2：您所说的这里主要是关于检索问题的角度适应性以及高度适应性的问题。NetVLAD的检索基于基础的CNN feature，这里我们实验也发现其对于较大程度的偏航角度无法很好处理。其实并不只是NetVLAD方法，在对于含有较大航向差异的数据集VPAir的测试过程中，基于CNN的方法均未能实现较好检索结果（可参考 [连接](https://paperswithcode.com/sota/visual-place-recognition-on-vp-air)）。因此对于旋转的适应性目前暂时并没有解决，我们公开的数据，对于遥感地图库也是航向预先对齐了。对于尺度的适应性其实也可以通过对于数据库的选择这步骤进行一定的解决，例如我们在[仓库](https://github.com/hmf21/AerialVL)公开的数据库也都是含有三个不同高度的数据，来适应高度的变化。对于高度差异很大的情况，由于景物基本差异很大，也没有从算法端很好的解决方法。
问题3：我们这里聚类中心点参数量并不是很大，设定聚类数量64或者32，聚类中心向量几万维，整体储存不会超过十几MB。反倒是检索任务需要将地图数据库加载进内存中，这里如果维度较大，地图库数量较多，可能是GB级别的内存占用，实际部署是一个难题。目前我们也是使用较好的Jetson端侧设备来部署，保证GPU资源充足。

**Comment by huangk77** [comment]
感谢您的详细回复以及启发，我会进一步研究一下关于旋转和尺度的问题，再次感谢，同时祝您论文、工作顺利~

**Comment by hmf21** [comment]
Hi @huangk77 
您客气了，这部分旋转的工作我们课题组目前也有同学正在跟进，目前已经有一定的效果，论文公开我会及时向您通知

**Comment by huangk77** [comment]
感谢，我觉得无人机视觉定位是一件有意义并且目前仍存在很多研究方向的工作，特别是在性能以及传感器受限的设备上，我也会持续跟进，期待你们的最新工作，respect~
